### ISSUE TITLE
Text fragments left on Addons list

### ISSUE THREAD

**Issue by webbird** [BlackCatDevelopment/BlackCatCMS#219]
![2014-02-13_125853](https://f.cloud.github.com/assets/147354/2159468/583ccb5c-94a6-11e3-8a36-e0f98fe6e789.png)

This MAY be a browser problem. (?)

**Comment by webbird** [comment]
I have never seen this, maybe a hardware problem? I leave this open, but I think there's nothing we can do.

**Comment by Morpheus1966** [comment]
It is no longer occurred. Please close

**Comment by webbird** [comment]
Okay. You can open a new one if you see it again.
