### ISSUE TITLE
Mojito Template: basic.css breaks Lightbox

### ISSUE THREAD

**Issue by webbird** [BlackCatDevelopment/BlackCatCMS#282]
In basic.css there is this:

img {   margin: 1%; }

This breaks the prettyPhoto lightbox, see screenshots:

NOT OK:
![2014-12-09_141309](https://cloud.githubusercontent.com/assets/147354/5357871/a974ae70-7fad-11e4-8971-3ef56c099938.png)

(nearly) OK:
![2014-12-09_141349](https://cloud.githubusercontent.com/assets/147354/5357870/a96e65a6-7fad-11e4-88e7-cb224da8e927.png)

**Comment by creativecat** [comment]
In my opinion this is a problem of Lightbox itself originally. But I will remove this value from CSS so everything works fine. In this case you have to add separate margin to each image you add to text.
