### ISSUE TITLE
Dashboard is broken - Unable to connect to SSL

### ISSUE THREAD

**Issue by creativecat** [BlackCatDevelopment/BlackCatCMS#360]
As we changed our URL to http**s** the widgets for version check and forum news are not able to connect to http any more.

**Comment by creativecat** [comment]
Seems to be this issue https://github.com/zendframework/zendframework/pull/5870

**Comment by creativecat** [comment]
I modified the .htaccess on our server to enable the version file over standard http - should work but there should be a solution to enable the access over https as well.

**Comment by webbird** [comment]
I made a new version of check.php (version check widget) to use GitHub instead of version.txt. As for the forum, you can add

'sslverifypeer' => false

though it's not "as intended by the inventor".

**Comment by webbird** [comment]
Fixed by replacing Zend with CUrl.
