### ISSUE TITLE
Trying to install add on over build in catalog

### ISSUE THREAD

**Issue by creativecat** [BlackCatDevelopment/BlackCatCMS#369]
When clicking on the button "catalog" in the add-on section I get a fatal error:
"BlackCat CMS Fatal Error
Es ist leider ein Problem beim Bearbeiten Ihrer Anfrage aufgetreten!
Fehlermeldung:
Fehler beim Darstellen der Seite
Quelle: [ DriverDecorator.php : 79 : get ]"

The website is using SSL. Maybe this causes the error?

**Comment by webbird** [comment]
I am using SSL too, AND behind proxy, no problems. This is a template error. Maybe the script is missing from the class_secure table?

**Comment by creativecat** [comment]
By now I can't reproduce this error anymore... I tried on several installations. As there is no one else having this issue we can close it.
