### ISSUE TITLE
version 1.3

### ISSUE THREAD

**Issue by carrie0307** [BlackCatDevelopment/BlackCatCMS#375]
Execuse me, when I installed your package here and visited "BlackCatCMS/upload/backend/start/index.php", the page says "Local version 1.3" . So I wanna know has the version been updated ? 

Thank you very much !

**Comment by creativecat** [comment]
The current version is 1.3 - that's correct.

**Comment by carrie0307** [comment]
Thank you ,I got it~

**Comment by webbird** [comment]
What version did you expect? Is there something wrong anywhere?

**Comment by creativecat** [comment]
Can we close this?
