### ISSUE TITLE
Install module manually

### ISSUE THREAD

**Issue by creativecat** [BlackCatDevelopment/BlackCatCMS#376]
When trying to install a module manually (upload the module via FTP and install later), you get a "CSRF check failed. Your form session may have expired, or you may not have cookies enabled.". After clicking "Try again" everything works fine.

**Comment by creativecat** [comment]
I couldn't reproduce that behavior any more... Anyone?

**Comment by webbird** [comment]
It is gone with v1.4 as we removed the csrf-magic integration.
