### ISSUE TITLE
v1.3.3: Fehler beim Verschieben von Seiten

### ISSUE THREAD

**Issue by webbird** [BlackCatDevelopment/BlackCatCMS#386]
Wird eine Seite mit Unterseiten in der Hierarchie verschoben, indem ihr eine neue übergeordnete Seite zugeordnet wird, werden zwar die "access files" korrekt erzeugt, jedoch werden die Einträge in der pages-Tabelle nicht angepaßt. Dadurch stimmt beispielsweise der Seitenlink nicht mehr. Zudem lassen sich die Seiteneigenschaften nicht mehr speichern, weil die Meldung kommt, dass bereits eine gleichnamige Seite existiert.

**Comment by creativecat** [comment]
Ist der Bug noch offen? Ich glaube nicht, oder?

**Comment by webbird** [comment]
Ja, doch, das ist immer noch so.

![2020-08-10 09_53_50-BC1 3 6_bc135_cat_pages_ - HeidiSQL Portable 9 5 0 5196](https://user-images.githubusercontent.com/147354/89761797-7bf64f00-daef-11ea-8334-59f92a024480.png)

Hier habe ich "Bootstrap Test" mit "Unterseite 1" und "Unterseite 2" nach "Tests" verschoben. Der Link für "Bootstrap Test" wurde angepaßt, aber nicht für die beiden Unterseiten.

**Comment by creativecat** [comment]
Ok, dann schau ich morgen spätestens Donnerstag noch einmal auf den Fehler.

**Comment by webbird** [comment]
Sollte gefixt sein. Sorry, hab nicht gesehen dass Du das machen wolltest. ;D
