### ISSUE TITLE
v1.4Beta: Unable to change user password (not saved)

### ISSUE THREAD

**Issue by webbird** [BlackCatDevelopment/BlackCatCMS#396]
Wenn ein Admin das Kennwort eines Benutzers ändern will, wird das nicht gespeichert. Fehlt in ajax_save_user.php.

**Comment by creativecat** [comment]
Ich glaube, dass das mit dem OTP zusammenhängt. Ich kann gerade in meiner Testinstallation auch keinen neuen Benutzer anlegen: 
`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'otp' at row 1`

**Comment by creativecat** [comment]
Ok, ich hab das noch mal getestet. Es scheint nur das OTP nicht korrekt markiert zu werden. 
Das scheint am Datentyp bit(1) für top zu liegen. Ich habe das mal auf tinyint(1) geändert und damit funktioniert das einwandfrei. Passe ich morgen im Installer bzw Updater an und dann sollte das Problem behoben sein!
