### ISSUE TITLE
v1.4Beta: Unable to login with newly hashed password

### ISSUE THREAD

**Issue by webbird** [BlackCatDevelopment/BlackCatCMS#397]
Mit dem ersten erfolgreichen Login wird die Kennwortverschlüsselung von MD5 auf password_hash() geändert. Das klappt nach einem Update einer 1.3.6 bei Ionos nicht. Man kann sich genau noch einmal anmelden und danach nie mehr.

**Comment by creativecat** [comment]
Kannst du das mit der aktuellen Version noch mal testen? Hab da gestern noch ein bisschen dran gebastelt, weil ich ebenfalls nach einem Update Probleme mit dem Login hatte.
Hast du überprüft, dass das Passwort beim richtigen Benutzer neu gehashed wurde?
