### ISSUE TITLE
installation comple but cat_addons error received

### ISSUE THREAD

**Issue by kemrec** [BlackCatDevelopment/BlackCatCMS#403]
[DB Exception] [SQL Error] SELECT * FROM `cat_addons` WHERE type = 'template' AND function = 'template' ORDER BY 'type' ASC, 'name' ASC this error shown when user:password correct login try, but when user:passwd wrong entered, there is no error, user:passwd wrong screen appears.

whatis wrong with me?
![bb1](https://user-images.githubusercontent.com/25618690/94362826-93e95880-00c6-11eb-8c71-b632d96d9f24.PNG)

**Comment by webbird** [comment]
Can you please try to execute the SELECT statement on the database directly, using phpMyAdmin or whatever tool your provider offers for database administration?

```
SELECT * FROM `cat_addons` WHERE type = 'template' AND function = 'template' ORDER BY 'type' ASC, 'name' ASC
```

Does database table "cat_addons" exist? 
Do the colums "function" and "type" exist in that table?
Which version of mysql/mariaDB do you use?

**Comment by webbird** [comment]
Never got reply
