### ISSUE TITLE
🚨 Potential Security Vulnerability - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [BlackCatDevelopment/BlackCatCMS#409]
#### ⚠️ Potential Vulnerability in BlackCatCMS

👋 Hello, @creativecat, @webbird, @hertsch - @aydinnyunus has disclosed a potential vulnerability in your repository. To validate or invalidate this potential vulnerability, please visit https://huntr.dev/bounties/2-other-BlackCatCMS and join our community in helping secure open-source code.

---

#### ☎️ Need further support?

Come and join us on our [Discord](https://huntr.dev/discord) and a member of our team will be happy to help! 🤗

cc - @JamieSlome

**Comment by webbird** [comment]
I don't want to register somewhere to get details about a potential vulnerability.

**Comment by aydinnyunus** [comment]
Even though vulnerability details are on github, you're not interested anyway lol

https://github.com/BlackCatDevelopment/BlackCatCMS/issues/408
