### ISSUE TITLE
Global defaults for non-styled elements

### ISSUE THREAD

**Issue by webbird** [BlackCatDevelopment/BlackCatCMS#57]
As the freshcat CSS includes a reset.css, the defaults for forms (for example) look not very well. There should be some nice looking defaults for fieldsets, legends, and so on.

**Comment by webbird** [comment]
If there *will* be a Freshcat Theme in BC2, this should be fixed there.

**Comment by creativecat** [comment]
I will add this to a new (complete reworked) FreshCat in BC2!
